umbrella:
  serverId: ""
  licenseKey: ""

  plugins: []

postgresql:
  enabled: true
  # postgresqlHostname:
  # postgresqlPort: 5432
  postgresqlDatabase: crowd
  postgresqlUsername: crowd
  postgresqlPassword: crowd
  postgresqlPostgresPassword: crowd
