global:
  postgresql:
    postgresqlHostname: ""
    postgresqlDatabase: ""
    postgresqlUsername: ""
    postgresqlPassword: ""
    servicePort: ""

umbrella:
  initDB: false
  serverId: ""
  licenseKey: ""
  plugins: []

crowd:
  # make 4.3.5-jdk11 default (as stated in upstream's Chart.yaml)
  image:
    tag: 4.3.5-jdk11

postgresql:
  enabled: true
  postgresqlDatabase: crowd
  postgresqlUsername: crowd
  postgresqlPassword: crowd
  postgresqlPostgresPassword: crowd
