{{- if .Values.idpMetadataContent }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "central-saml-logout.fullname" . }}-config-idp-metadata
  {{- with .Values.annotations }}
  annotations:
  {{- range $key, $value := . }}
  {{- printf "%s: %s" $key (tpl $value $ | quote) | nindent 4 }}
  {{- end }}
  {{- end }}
  labels:
  {{- include "central-saml-logout.labels" $ | nindent 4 }}
  {{- range $key, $value := .Values.labels }}
  {{- printf "%s: %s" $key (tpl $value $ | quote) | nindent 4 }}
  {{- end }}
data:
  idp-metadata.xml: '{{ tpl .Values.idpMetadataContent . }}'
{{- end }}
