{{- if .Values.route.enabled -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "central-saml-logout.fullname" . }}
  {{- with .Values.route.annotations }}
  annotations:
    {{- range $key, $value := . }}
    {{- printf "%s: %s" $key (tpl $value $ | quote) | nindent 4 }}
    {{- end }}
  {{- end }}
  labels:
    {{- include "central-saml-logout.labels" . | nindent 4 }}
    {{- range $key, $value := .Values.route.labels }}
    {{- printf "%s: %s" $key (tpl $value $ | quote) | nindent 4 }}
    {{- end }}
spec:
{{- if .Values.route.host }}
  host: {{ tpl .Values.route.host $ | quote }}
{{- end }}
  path: {{ .Values.route.path }}
  port:
    {{- if or (not .Values.route.tls.enabled) (eq .Values.route.tls.termination "edge") }}
    targetPort: http
    {{- else}}
    targetPort: https
    {{- end}}
  to:
    kind: Service
    name: {{ include "central-saml-logout.fullname" $ }}-http
    weight: 100
  {{- if .Values.route.tls.enabled }}
  tls:
    insecureEdgeTerminationPolicy: {{ .Values.route.tls.insecureEdgeTerminationPolicy }}
    termination: {{ .Values.route.tls.termination }}
  {{- end }}
{{- end -}}
