apiVersion: v2
name: keycloak-umbrella
version: 15.1.1
appVersion: 15.1.0
description: Helm chart for Keycloak with PostgreSQL and settings customization
type: application
sources:
  - https://github.com/aservo/charts
  - https://github.com/codecentric/helm-charts
  - https://github.com/aservo/docker-networking
  - https://github.com/jboss-dockerfiles/keycloak
  - https://github.com/keycloak/keycloak
dependencies:
  - name: keycloak
    version: 15.1.0
    repository: https://codecentric.github.io/helm-charts
maintainers:
  - name: ASERVO Software GmbH
    email: opensource@aservo.com
engine: gotpl
