apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ldap-crowd-adapter.fullname" . }}-secret-env
  {{- with .Values.annotations }}
  annotations:
  {{- range $key, $value := . }}
  {{- printf "%s: %s" $key (tpl $value $ | quote) | nindent 4 }}
  {{- end }}
  {{- end }}
  labels:
  {{- include "ldap-crowd-adapter.labels" $ | nindent 4 }}
  {{- range $key, $value := .Values.labels }}
  {{- printf "%s: %s" $key (tpl $value $ | quote) | nindent 4 }}
  {{- end }}
type: {{ default "Opaque" .Values.type }}
data:
  {{- with .Values.ssl.keyStorePassword }}
  SERVER_SSL_KEY_STORE_PASSWORD: '{{ . | b64enc }}'
  {{- end }}
  {{- with .Values.ssl.crt }}
  SSL_CRT: '{{ . | b64enc }}'
  {{- end }}
  {{- with .Values.ssl.key }}
  SSL_KEY: '{{ . | b64enc }}'
  {{- end }}
  {{- with .Values.crowd.applicationPassword }}
  CROWD_APP_PASSWORD: '{{ . | b64enc }}'
  {{- end }}
  {{- with .Values.backend.crowd.adminRest.username }}
  BACKEND_REST_USERNAME: '{{ . | b64enc }}'
  {{- end }}
  {{- with .Values.backend.crowd.adminRest.userPassword }}
  BACKEND_REST_USER_PASSWORD: '{{ . | b64enc }}'
  {{- end }}
  {{- with .Values.backend.db.connection.user }}
  BACKEND_JDBC_USER: '{{ . | b64enc }}'
  {{- end }}
  {{- with .Values.backend.db.connection.password }}
  BACKEND_JDBC_PASSWORD: '{{ . | b64enc }}'
  {{- end }}
