apiVersion: v1
kind: Secret
metadata:
  name: jira-secrets
  labels:
  {{- include "umbrella.labels" . | nindent 4 }}
type: Opaque
data:
  postgresql-password: "{{ .Values.postgresql.postgresqlPassword | b64enc }}"