apiVersion: v1
kind: Secret
metadata:
  name: {{ include "jira.fullname" .Subcharts.jira }}-secrets
  labels:
  {{- include "umbrella.labels" . | nindent 4 }}
type: Opaque
data:
  postgresql-url: {{ printf "jdbc:postgresql://%s:%s/%s" (include "umbrella.databaseHost" .) (include "umbrella.databasePort" .) (include "umbrella.databaseName" .) | b64enc | quote }}
  postgresql-username: {{ include "umbrella.databaseUser" . | b64enc | quote }}
  postgresql-password: {{ include "umbrella.databasePassword" . | b64enc | quote }}
  license-key: {{ include "umbrella.licenseKey" . | b64enc | quote }}
