apiVersion: v2
name: jira-umbrella
version: 0.11.1
appVersion: 8.13.6-jdk11
description: Helm chart for Jira with Postgresql, plugins and parametrization
type: application
sources:
  - https://github.com/aservo/charts
  - https://github.com/atlassian/data-center-helm-charts/tree/main/src/main/charts/jira
  - https://github.com/bitnami/charts/tree/master/bitnami/postgresql
dependencies:
  - name: jira
    version: 0.11.0
    repository: https://atlassian.github.io/data-center-helm-charts
  - name: postgresql
    version: 10.3.17
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
maintainers:
  - name: ASERVO Software GmbH
    email: opensource@aservo.com
engine: gotpl