umbrella:
  serverId: ""

jira:
  volumes:
    additional:
      # -- Volume with additional configuration files
      - name: jira-config
        configMap:
          name: jira-config
          items:
          - key: restore-db.sh
            path: restore-db.sh
            mode: 0755
          - key: dbconfig.xml
            path: dbconfig.xml
            mode: 0755
          - key: server.xml
            path: server.xml
            mode: 0755
          - key: seraph-config.xml
            path: seraph-config.xml
            mode: 0755

      # -- Volume with additional dump file for SQL import to the database
      - name: dump-config
        configMap:
          name: dump-config
          items:
          - key: db.dump
            path: db.dump

  additionalInitContainers:
    # -- Additional initContainer to copy the Jira configuration.
    # Copies dbconfig.xml file to the proper location
    - name: copy-config
      image: busybox
      imagePullPolicy: IfNotPresent
      command:
        - /bin/sh
      args:
        - '-c'
        - >-
          set -x &&
          mkdir -p /opt/atlassian/jira/conf/ &&
          cp /tmp/server.xml /opt/atlassian/jira/conf/server.xml &&
          cp /tmp/dbconfig.xml /var/atlassian/application-data/jira/dbconfig.xml &&
          cp /tmp/dbconfig.xml /var/atlassian/application-data/shared-home/dbconfig.xml &&
          mkdir -p /opt/atlassian/jira/atlassian-jira/WEB-INF/classes/ &&
          cp /tmp/seraph-config.xml /opt/atlassian/jira/atlassian-jira/WEB-INF/classes/seraph-config.xml &&
          chown 2001:2001 /var/atlassian/application-data/jira/dbconfig.xml &&
          chown 2001:2001 /var/atlassian/application-data/shared-home/dbconfig.xml &&
          chown 2001:2001 /opt/atlassian/jira/conf/server.xml &&
          chown 2001:2001 /opt/atlassian/jira/atlassian-jira/WEB-INF/classes/seraph-config.xml
      resources: {}
      volumeMounts:
        - name: jira-config
          mountPath: /tmp/dbconfig.xml
          subPath: dbconfig.xml
        - name: jira-config
          mountPath: /tmp/server.xml
          subPath: server.xml
        - name: jira-config
          mountPath: /tmp/seraph-config.xml
          subPath: seraph-config.xml
        - name: local-home
          mountPath: /var/atlassian/application-data/jira
        - name: shared-home
          mountPath: /var/atlassian/application-data/shared-home

    # -- Additional initContainer to load initial Jira database.
    # The initial Jira setup was performed in order to connect to a ready Postgresql database
    # After the chart deployment the default user is able immediately to login without init routine
    - name: init-db
      image: docker.io/bitnami/postgresql:11
      imagePullPolicy: IfNotPresent
      resources: {}
      volumeMounts:
        - name: jira-config
          mountPath: /tmp/restore-db.sh
          subPath: restore-db.sh
        - name: dump-config
          mountPath: /tmp/db.dump
          subPath: db.dump
      env:
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: jira-secrets
              key: postgresql-password
      args: ['/tmp/restore-db.sh']

# -- Bitnami PostgreSQL helm chart
postgresql:
  enabled: true
  # postgresqlHostname:
  postgresqlPort: 5432
  postgresqlDatabase: jira
  postgresqlUsername: jira
  postgresqlPassword: jira
  postgresqlPostgresPassword: jira