global:
  postgresql:
    postgresqlHostname: ""
    postgresqlDatabase: ""
    postgresqlUsername: ""
    postgresqlPassword: ""
    servicePort: ""

umbrella:
  serverId: ""
  licenseKey: ""

postgresql:
  enabled: true
  postgresqlDatabase: jira
  postgresqlUsername: jira
  postgresqlPassword: jira
  postgresqlPostgresPassword: jira
