umbrella:
  serverId: ""
  licenseKey: ""

postgresql:
  enabled: true
  # postgresqlHostname:
  postgresqlPort: 5432
  postgresqlDatabase: jira
  postgresqlUsername: jira
  postgresqlPassword: jira
  postgresqlPostgresPassword: jira