global:
  postgresql:
    postgresqlHostname: ""
    postgresqlDatabase: ""
    postgresqlUsername: ""
    postgresqlPassword: ""
    servicePort: ""

umbrella:
  initDB: false
  serverId: ""
  licenseKey: ""

## Jira chart configuration
## ref: https://github.com/atlassian/data-center-helm-charts/blob/main/src/main/charts/jira/values.yaml
##
jira:
  database: {}  # this section of the 'jira' subchart is disabled in this 'umbrella' chart
  license: {}  # this section of the 'jira' subchart should not be used in this 'umbrella' chart

## PostgreSQL chart configuration
## ref: https://github.com/bitnami/charts/blob/master/bitnami/postgresql/values.yaml
##
postgresql:
  enabled: true
  postgresqlDatabase: jira
  postgresqlUsername: jira
  postgresqlPassword: jira
  postgresqlPostgresPassword: jira
