apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "umbrella.fullname" . }}
  {{- with .Values.annotations }}
  annotations:
    {{- range $key, $value := . }}
    {{- printf "%s: %s" $key (tpl $value $ | quote) | nindent 4 }}
    {{- end }}
  {{- end }}
  labels:
    {{- include "umbrella.labels" . | nindent 4 }}
    {{- range $key, $value := .Values.labels }}
    {{- printf "%s: %s" $key (tpl $value $ | quote) | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "umbrella.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.keycloak.podAnnotations }}
      annotations:
        {{- range $key, $value := . }}
        {{- printf "%s: %s" $key (tpl $value $ | quote) | nindent 8 }}
        {{- end }}
      {{- end }}
      labels:
        {{- include "umbrella.labels" . | nindent 8 }}
        {{- range $key, $value := .Values.keycloak.podLabels }}
        {{- printf "%s: %s" $key (tpl $value $ | quote) | nindent 8 }}
        {{- end }}
    spec:
      containers:
        - name: {{ template "umbrella.fullname" . }}-customization
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/opt/realm-import.sh"]
          args: ["/opt/realm-config.json"]
          env:
            {{- with .Values.keycloak.extraEnv }}
            {{- tpl . $ | nindent 12 }}
            {{- end }}
          envFrom:
            {{- with .Values.keycloak.extraEnvFrom }}
            {{- tpl . $ | nindent 12 }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: {{ template "umbrella.fullname" . }}-config
              mountPath: "/opt/realm-config.json"
              subPath: "realm-config.json"
            - name: {{ template "umbrella.fullname" . }}-config
              mountPath: "/opt/realm-import.sh"
              subPath: "realm-import.sh"
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.securityContext | nindent 8 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      volumes:
        - name: {{ template "umbrella.fullname" . }}-config
          configMap:
            name: {{ .Release.Name }}-config
            defaultMode: 0444
            items:
              - key: realm-config.json
                path: realm-config.json
                mode: 0444
              - key: realm-import.sh
                path: realm-import.sh
                mode: 0555
