apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-realm-secret
  {{- with .Values.annotations }}
  annotations:
      {{- range $key, $value := . }}
        {{- printf "%s: %s" $key (tpl $value $ | quote) | nindent 4 }}
    {{- end }}
  {{- end }}
  labels:
    {{- include "umbrella.labels" . | nindent 4 }}
      {{- range $key, $value := .Values.labels }}
      {{- printf "%s: %s" $key (tpl $value $ | quote) | nindent 4 }}
      {{- end }}
type: Opaque
data:
  realm-config.json: {{ .Values.umbrella.realmConfig | toJson | b64enc }}
