global:
  postgresql:
    postgresqlHostname: ""
    postgresqlDatabase: ""
    postgresqlUsername: ""
    postgresqlPassword: ""
    servicePort: ""

umbrella:
  serverId: ""
  licenseKey: ""

postgresql:
  enabled: true
  postgresqlDatabase: confluence
  postgresqlUsername: confluence
  postgresqlPassword: confluence
  postgresqlPostgresPassword: confluence
  postgresqlMaxConnections: 125
