umbrella:
  serverId: ""
  licenseKey: ""

postgresql:
  enabled: true
  # postgresqlHostname:
  # postgresqlPort: 5432
  postgresqlDatabase: confluence
  postgresqlUsername: confluence
  postgresqlPassword: confluence
  postgresqlPostgresPassword: confluence
  postgresqlMaxConnections: 125