name: CI

on: pull_request

env:
  ENV_FILE: .env

jobs:

  tests:

    runs-on: ubuntu-latest

    timeout-minutes: 15

    strategy:
      matrix:
        kubernetes_version:
          - "1.20.7"
          - "1.19.11"
          - "1.18.19"
      fail-fast: false

    env:
      KUBERNETES_VERSION: ${{ matrix.kubernetes_version }}

    steps:

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Load environment variables from .env file
        shell: bash
        run: |
          while read line; do
            echo "$line" >> $GITHUB_ENV
          done < ${{ env.ENV_FILE }}

      - name: Install Kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: v${{ env.KUBECTL_VERSION }}

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: ${{ env.HELM_VERSION }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.0.1
        with:
          version: v${{ env.CHART_TESTING_VERSION }}

      - name: Set AKS Kubectl Context
        uses: azure/aks-set-context@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          resource-group: gha-k8s-cluster-rg
          cluster-name: gha-k8s-cluster

      - name: List changed charts
        id: list-changed
        run: |
          changed=$(ct list-changed --config ct.yaml)
          if [[ -n "$changed" ]]; then
            echo "::set-output name=changed::true"
          fi
          echo $changed

      - name: Lint changed charts
        run: ct lint --config ct.yaml

      - name: Install Helm unittest plugin
        if: steps.list-changed.outputs.changed == 'true'
        run: |
          helm env
          helm plugin install https://github.com/quintush/helm-unittest --version 0.2.4

      # Currently not used because of this bug (and in meantime missing features):
      # https://github.com/helm/chart-testing/issues/332
      # - name: Run chart-testing (install)
      #   run: ct install --config ct.yaml

      - name: Install and test changed charts
        if: steps.list-changed.outputs.changed == 'true'
        run: |
          changed=$(ct list-changed --config ct.yaml | tr \\n ',')
          ./scripts/helm-install-test.sh ${changed%?}
