name: CI

on: pull_request

jobs:
  tests:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        kubernetes_version:
          # - "v1.22.2"
          - "v1.21.2"
          - "v1.20.7"
          - "v1.19.11"
          - "v1.18.19"
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.0.1
        with:
          version: v3.4.0

      - name: List changed charts
        id: list-changed
        run: |
          changed=$(ct list-changed --config ct.yaml)
          if [[ -n "$changed" ]]; then
            echo "::set-output name=changed::true"
          fi
          echo $changed

      - name: Lint changed charts
        run: ct lint --config ct.yaml

      - name: Create kind cluster
        uses: helm/kind-action@v1.2.0
        if: steps.list-changed.outputs.changed == 'true'
        with:
          version: v0.11.1
          node_image: kindest/node:${{ matrix.kubernetes_version }}

      - name: Run chart-testing (install)
        run: ct install --config ct.yaml
